name: personal_dev_portfolio
description: My Personal Development Portfolio Made With Flutter.



publish_to: "none" 











version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.4
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:
  
  
  
  uses-material-design: true

  
  assets:
    - assets/icons/
    - assets/images/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
