name: personal_dev_portfolio
description: My Personal Development Portfolio Made With Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0
  flutter_svg: ^1.1.6
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.5.0
  get: ^4.6.5
  url_launcher: ^6.1.12
  animated_theme_switcher: ^2.0.8
  firebase_core: ^1.24.0
#  cloud_firestore: ^3.1.10
#  firebase_storage: ^10.2.9
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
