// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBujzrgGuU3mR6LD8V3YRFoWPjpMITkCBg',
    appId: '1:815291183245:web:3fc838f1d8f8e315cc72c4',
    messagingSenderId: '815291183245',
    projectId: 'moaz-dev',
    authDomain: 'moaz-dev.firebaseapp.com',
    storageBucket: 'moaz-dev.appspot.com',
    measurementId: 'G-82P6GQFG8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf1UF2XWPtjBlcVPLCHDpRBwVUQw6Cpcg',
    appId: '1:815291183245:android:277fcb57b4c76796cc72c4',
    messagingSenderId: '815291183245',
    projectId: 'moaz-dev',
    storageBucket: 'moaz-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA73V4xbfi5cOIYtgUo2yOlH_BbFt6wW0g',
    appId: '1:815291183245:ios:b78e224e03e8cf60cc72c4',
    messagingSenderId: '815291183245',
    projectId: 'moaz-dev',
    storageBucket: 'moaz-dev.appspot.com',
    iosClientId: '815291183245-996l3ermq5lg7vbvlhkq18s0m1p12st5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA73V4xbfi5cOIYtgUo2yOlH_BbFt6wW0g',
    appId: '1:815291183245:ios:b78e224e03e8cf60cc72c4',
    messagingSenderId: '815291183245',
    projectId: 'moaz-dev',
    storageBucket: 'moaz-dev.appspot.com',
    iosClientId: '815291183245-996l3ermq5lg7vbvlhkq18s0m1p12st5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProfile',
  );
}
